import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import About from '../components/About'
import AboutMe from '@/components/AboutMe'
import Box from '../styles/components/AOSWrapper/styles'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div data-aos='fade-up' data-aos-duration='3000'>
          <Header  />
        </div>
        <div data-aos='fade-right' data-aos-duration='3000'>
          <About />
        </div>
        <div data-aos='fade-left' data-aos-duration='3000'>
          <AboutMe  />
        </div>
      </main>
    </>
  )
}
